<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class EmployeeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $employees = [
            [
                'nama_lengkap' => 'Alhabib Adelia Saputra',
                'nomor_ktp' => '3318021411960005',
                'email' => 'alhabib.adelia@jsclab.id',
                'username_vpn' => 'dev-alhabib',
                'posisi_jabatan' => 'Technical Writer',
                'nama_organisasi' => 'Jakarta Smart City',
                'nomer_hp_wa' => '089619794883',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lengkap' => 'Andika Bayhaki AL',
                'nomor_ktp' => '3507181710980003',
                'email' => 'andika.bayhaki@jsclab.id',
                'username_vpn' => 'dev-andika',
                'posisi_jabatan' => 'Project Leader',
                'nama_organisasi' => 'Jakarta Smart City',
                'nomer_hp_wa' => '082233818665',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lengkap' => 'Annisa Tahira',
                'nomor_ktp' => '3271046511950020',
                'email' => 'annisa.tahira@jsclab.id',
                'username_vpn' => 'dev-annisa',
                'posisi_jabatan' => 'Frontend',
                'nama_organisasi' => 'Jakarta Smart City',
                'nomer_hp_wa' => '082298532311',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lengkap' => 'Arif Ramadani',
                'nomor_ktp' => '3276060308940004',
                'email' => 'arif.ramadani@jsclab.id',
                'username_vpn' => 'dev-arif',
                'posisi_jabatan' => 'Technical Writer',
                'nama_organisasi' => 'Jakarta Smart City',
                'nomer_hp_wa' => '0895376438233',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lengkap' => 'Bagas Hadi Prakoso',
                'nomor_ktp' => '3174100506950003',
                'email' => 'bagas.hadi@jsclab.id',
                'username_vpn' => 'dev-bagas',
                'posisi_jabatan' => 'Backend',
                'nama_organisasi' => 'Jakarta Smart City',
                'nomer_hp_wa' => '085945133344',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lengkap' => 'Celsa Bella',
                'nomor_ktp' => '1308057009970004',
                'email' => 'celsa.bella@jsclab.id',
                'username_vpn' => 'dev-celsa',
                'posisi_jabatan' => 'Quality Assurance',
                'nama_organisasi' => 'Jakarta Smart City',
                'nomer_hp_wa' => '082283099854',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lengkap' => 'Dida Putra Perdana',
                'nomor_ktp' => '3174012801930001',
                'email' => 'dida.putra@jsclab.id',
                'username_vpn' => 'dev-dida',
                'posisi_jabatan' => 'Assisten PL',
                'nama_organisasi' => 'Jakarta Smart City',
                'nomer_hp_wa' => '08988262024',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lengkap' => 'Dwikky Maradhiza Yudakusuma',
                'nomor_ktp' => '3674022103910002',
                'email' => 'dwikky.maradhiza@jsclab.id',
                'username_vpn' => 'dev-dwikky',
                'posisi_jabatan' => 'Backend',
                'nama_organisasi' => 'Jakarta Smart City',
                'nomer_hp_wa' => '081250003121',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lengkap' => 'Edith Pradipta Nugroho',
                'nomor_ktp' => '3175051601920007',
                'email' => 'edith.pradipta@jsclab.id',
                'username_vpn' => 'dev-edith',
                'posisi_jabatan' => 'Quality Assurance',
                'nama_organisasi' => 'Jakarta Smart City',
                'nomer_hp_wa' => '085697478956',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lengkap' => 'Eko Setyawan',
                'nomor_ktp' => '3501111512890003',
                'email' => 'eko.setyawan@jsclab.id',
                'username_vpn' => 'dev-eko',
                'posisi_jabatan' => 'Mobile Developer',
                'nama_organisasi' => 'Jakarta Smart City',
                'nomer_hp_wa' => '087758855444',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lengkap' => 'Erwin Cesar',
                'nomor_ktp' => '3175101502870005',
                'email' => 'erwin.cesar@jsclab.id',
                'username_vpn' => 'dev-erwin',
                'posisi_jabatan' => 'Mobile Developer',
                'nama_organisasi' => 'Jakarta Smart City',
                'nomer_hp_wa' => '081333000556',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lengkap' => 'Fahmi Rahmadi',
                'nomor_ktp' => '3173052103940017',
                'email' => 'fahmi.rahmadi@jsclab.id',
                'username_vpn' => 'dev-fahmi',
                'posisi_jabatan' => 'IT Helpdesk',
                'nama_organisasi' => 'Jakarta Smart City',
                'nomer_hp_wa' => '085710244653',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lengkap' => 'Fajar Aprian Koswara',
                'nomor_ktp' => '3216062804940013',
                'email' => 'fajar.aprian@jsclab.id',
                'username_vpn' => 'dev-fajar',
                'posisi_jabatan' => 'Technical Writer',
                'nama_organisasi' => 'Jakarta Smart City',
                'nomer_hp_wa' => '08158365856',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lengkap' => 'Farhan Fahrezi',
                'nomor_ktp' => '3603283003960002',
                'email' => 'farhan.fahrezi@jsclab.id',
                'username_vpn' => 'dev-farhan',
                'posisi_jabatan' => 'Quality Assurance',
                'nama_organisasi' => 'Jakarta Smart City',
                'nomer_hp_wa' => '087827626122',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lengkap' => 'Haris Yutri',
                'nomor_ktp' => '3216061012950007',
                'email' => 'haris.yutri@jsclab.id',
                'username_vpn' => 'dev-haris',
                'posisi_jabatan' => 'Frontend',
                'nama_organisasi' => 'Jakarta Smart City',
                'nomer_hp_wa' => '089658684921',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lengkap' => 'Hendry Priyatno',
                'nomor_ktp' => '3603143107900001',
                'email' => 'hendry.priyatno@jsclab.id',
                'username_vpn' => 'dev-hendry',
                'posisi_jabatan' => 'Backend',
                'nama_organisasi' => 'Jakarta Smart City',
                'nomer_hp_wa' => '081281101180',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lengkap' => 'Jody Dwi Antono',
                'nomor_ktp' => '3308112701950003',
                'email' => 'jody.dwi@jsclab.id',
                'username_vpn' => 'dev-jody',
                'posisi_jabatan' => 'Frontend',
                'nama_organisasi' => 'Jakarta Smart City',
                'nomer_hp_wa' => '085729499229',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lengkap' => 'Jofi Pamungkas',
                'nomor_ktp' => '350104041004930002',
                'email' => 'jofi.pamungkas@jsclab.id',
                'username_vpn' => 'dev-jofi',
                'posisi_jabatan' => 'IT Helpdesk',
                'nama_organisasi' => 'Jakarta Smart City',
                'nomer_hp_wa' => '082333445059',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lengkap' => 'Lia Aulia Susanti',
                'nomor_ktp' => '3276026010940010',
                'email' => 'lia.aulia@jsclab.id',
                'username_vpn' => 'dev-lia',
                'posisi_jabatan' => 'Quality Assurance',
                'nama_organisasi' => 'Jakarta Smart City',
                'nomer_hp_wa' => '085718604672',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lengkap' => 'M Farid Ridwan',
                'nomor_ktp' => '3174065202900002',
                'email' => 'm.farid@jsclab.id',
                'username_vpn' => 'dev-farid',
                'posisi_jabatan' => 'Project Leader',
                'nama_organisasi' => 'Jakarta Smart City',
                'nomer_hp_wa' => '085215363254',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lengkap' => 'M. Arie Yanuartaba',
                'nomor_ktp' => '3175021304940007',
                'email' => 'm.arie@jsclab.id',
                'username_vpn' => 'dev-arie',
                'posisi_jabatan' => 'Manager',
                'nama_organisasi' => 'Jakarta Smart City',
                'nomer_hp_wa' => '085810268074',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lengkap' => 'Maidy Cahyadi',
                'nomor_ktp' => '3173052104940001',
                'email' => 'maidy.cahyadi@jsclab.id',
                'username_vpn' => 'dev-maidy',
                'posisi_jabatan' => 'Quality Assurance',
                'nama_organisasi' => 'Jakarta Smart City',
                'nomer_hp_wa' => '082213626868',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lengkap' => 'Mirliyawan Ibrahim',
                'nomor_ktp' => '3175040406910002',
                'email' => 'mirliyawan.ibrahim@jsclab.id',
                'username_vpn' => 'dev-mirliyawan',
                'posisi_jabatan' => 'Mobile Developer',
                'nama_organisasi' => 'Jakarta Smart City',
                'nomer_hp_wa' => '081317385829',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lengkap' => 'Mohamad Hafitz Rizki',
                'nomor_ktp' => '3175013012900006',
                'email' => 'mohamad.hafitz@jsclab.id',
                'username_vpn' => 'dev-hafitz',
                'posisi_jabatan' => 'Project Leader',
                'nama_organisasi' => 'Jakarta Smart City',
                'nomer_hp_wa' => '089650873005',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lengkap' => 'Muhamad Alwi Shihab',
                'nomor_ktp' => '3175013012900007',
                'email' => 'muhamad.alwi@jsclab.id',
                'username_vpn' => 'dev-alwi',
                'posisi_jabatan' => 'Mobile Developer',
                'nama_organisasi' => 'Jakarta Smart City',
                'nomer_hp_wa' => '08561760292',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lengkap' => 'Muhamad Auliya Ahsan',
                'nomor_ktp' => '3276021802950005',
                'email' => 'm.auliya@jsclab.id',
                'username_vpn' => 'dev-ahsan',
                'posisi_jabatan' => 'Frontend',
                'nama_organisasi' => 'Jakarta Smart City',
                'nomer_hp_wa' => '085782787911',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lengkap' => 'Muhamad Nishafur Himmah A',
                'nomor_ktp' => '5171010103960004',
                'email' => 'muhamad.nishafur@jsclab.id',
                'username_vpn' => 'dev-shafur',
                'posisi_jabatan' => 'Project Leader',
                'nama_organisasi' => 'Jakarta Smart City',
                'nomer_hp_wa' => '085156285723',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lengkap' => 'Muhammad Nurmansyah Santosa',
                'nomor_ktp' => '3271041809930004',
                'email' => 'muhammad.nurmansyah@jsclab.id',
                'username_vpn' => 'dev-nurman',
                'posisi_jabatan' => 'Backend',
                'nama_organisasi' => 'Jakarta Smart City',
                'nomer_hp_wa' => '08568256957',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lengkap' => 'Nilam Maya Sari Tarigan',
                'nomor_ktp' => '3174065202900003',
                'email' => 'nilam.maya@jsclab.id',
                'username_vpn' => 'dev-nilam',
                'posisi_jabatan' => 'IT Helpdesk',
                'nama_organisasi' => 'Jakarta Smart City',
                'nomer_hp_wa' => '081294953700',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lengkap' => 'Putri Pratiwi S',
                'nomor_ktp' => '3174065202900004',
                'email' => 'putri.pratiwi@jsclab.id',
                'username_vpn' => 'dev-putri',
                'posisi_jabatan' => 'IT Helpdesk',
                'nama_organisasi' => 'Jakarta Smart City',
                'nomer_hp_wa' => '081318882712',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lengkap' => 'Renaldy Rizki Maulana',
                'nomor_ktp' => '3214031405960004',
                'email' => 'renaldy.rizki@jsclab.id',
                'username_vpn' => 'dev-renaldy',
                'posisi_jabatan' => 'Frontend',
                'nama_organisasi' => 'Jakarta Smart City',
                'nomer_hp_wa' => '085155182080',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lengkap' => 'Reza Ayatuna Lazuardy',
                'nomor_ktp' => '3175021304940008',
                'email' => 'reza.ayatuna@jsclab.id',
                'username_vpn' => 'dev-reza',
                'posisi_jabatan' => '',
                'nama_organisasi' => 'Jakarta Smart City',
                'nomer_hp_wa' => '085718541254',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lengkap' => 'Rizky Nuryandi',
                'nomor_ktp' => '3276051310920003',
                'email' => 'rizky.nuryandi@jsclab.id',
                'username_vpn' => 'dev-rizky',
                'posisi_jabatan' => '',
                'nama_organisasi' => 'Jakarta Smart City',
                'nomer_hp_wa' => '08117222747',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lengkap' => 'Robby Ali Darmawan',
                'nomor_ktp' => '3174060301910003',
                'email' => 'robby.ali@jsclab.id',
                'username_vpn' => 'dev-robby',
                'posisi_jabatan' => 'Mobile Developer',
                'nama_organisasi' => 'Jakarta Smart City',
                'nomer_hp_wa' => '081517218575',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lengkap' => 'Samuel Hasiholan',
                'nomor_ktp' => '3174092209930006',
                'email' => 'samuel.hasiholan@jsclab.id',
                'username_vpn' => 'dev-samuel',
                'posisi_jabatan' => '',
                'nama_organisasi' => 'Jakarta Smart City',
                'nomer_hp_wa' => '08561565552',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lengkap' => 'Sarinah Fitriah',
                'nomor_ktp' => '3276014604920002',
                'email' => 'sarinah.fitriah@jsclab.id',
                'username_vpn' => 'dev-sarinah',
                'posisi_jabatan' => 'IT Helpdesk',
                'nama_organisasi' => 'Jakarta Smart City',
                'nomer_hp_wa' => '089510878180',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lengkap' => 'Trinada Willya Citra',
                'nomor_ktp' => '1375035807950001',
                'email' => 'trinada.willya@jsclab.id',
                'username_vpn' => 'dev-trinada',
                'posisi_jabatan' => 'Project Leader',
                'nama_organisasi' => 'Jakarta Smart City',
                'nomer_hp_wa' => '085363232260',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lengkap' => 'Uki Priyanto',
                'nomor_ktp' => '3174065202900005',
                'email' => 'uki.priyanto@jsclab.id',
                'username_vpn' => 'dev-uki',
                'posisi_jabatan' => 'Devops',
                'nama_organisasi' => 'Jakarta Smart City',
                'nomer_hp_wa' => '085694242030',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lengkap' => 'Fachry Muhammad',
                'nomor_ktp' => '3277010303980017',
                'email' => 'fachry.muh@jsclab.id',
                'username_vpn' => 'dev-fachry',
                'posisi_jabatan' => 'Mobile Developer',
                'nama_organisasi' => 'Jakarta Smart City',
                'nomer_hp_wa' => '081299919198',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lengkap' => 'Giri Widyan Pratama',
                'nomor_ktp' => '3216071108930005',
                'email' => 'giri.widyan@jsclab.id',
                'username_vpn' => 'dev-giri',
                'posisi_jabatan' => 'Full Stack',
                'nama_organisasi' => 'Jakarta Smart City',
                'nomer_hp_wa' => '081213552057',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_lengkap' => 'Eric Thioko',
                'nomor_ktp' => '3174065202900006',
                'email' => 'eric.thioco@jsclab.id',
                'username_vpn' => 'dev-eric',
                'posisi_jabatan' => 'Frontend',
                'nama_organisasi' => 'Jakarta Smart City',
                'nomer_hp_wa' => '082139600035',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($employees as $employee) {
            try {
                DB::table('employees')->insert($employee);
                echo "Inserted: " . $employee['nama_lengkap'] . "\n";
            } catch (\Exception $e) {
                echo "Error inserting " . $employee['nama_lengkap'] . ": " . $e->getMessage() . "\n";
            }
        }
    }
}
