<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VpnServerSeederSmart extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get existing data to check for duplicates
        $existingServers = DB::table('vpn_servers')->pluck('ip_address')->toArray();
        
        // Original seeder data (all 193 entries)
        $originalData = [
            [
                'nama_sistem' => 'CRM Dev Docker Swarm',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.130',
                'project' => 'CRM v1 Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Jaki Dev Database MySQL',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.131',
                'project' => 'Jaki Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'CRM v1 Staging Rancher Cluster 1',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.127',
                'project' => 'CRM v1 Staging',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'CRM v1 Staging Rancher Cluster 2',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.141',
                'project' => 'CRM v1 Staging',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'CRM v1 Staging Rancher Cluster 3',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.106',
                'project' => 'CRM v1 Staging',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'CRM v1 Staging Database',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.224',
                'project' => 'CRM v1 Staging',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'CRM v1 Staging Rancher Cluster 4',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.142',
                'project' => 'CRM v1 Staging',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'CRM v1 Staging Rancher Cluster 5',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.143',
                'project' => 'CRM v1 Staging',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'CRM v1 Staging Database',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.107',
                'project' => 'CRM v1 Staging',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'CRM v1 Staging Minio',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.105',
                'project' => 'CRM v1 Staging',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'CRM v1 Staging Redis',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.118',
                'project' => 'CRM v1 Staging',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'CRM v1 Staging RabbitMQ',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.221',
                'project' => 'CRM v1 Staging',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'CRM v1 Prod Rancher Cluster 1',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.224',
                'project' => 'CRM v1 Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'CRM v1 Prod Rancher Cluster 2',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.142',
                'project' => 'CRM v1 Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'CRM v1 Prod Rancher Cluster 3',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.143',
                'project' => 'CRM v1 Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'CRM v1 Prod Rancher Cluster 4',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.107',
                'project' => 'CRM v1 Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'CRM v1 Prod Rancher Cluster 5',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.105',
                'project' => 'CRM v1 Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'CRM v1 Prod Database',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.107',
                'project' => 'CRM v1 Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'CRM v1 Prod Minio',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.105',
                'project' => 'CRM v1 Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'CRM v1 Prod Redis',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.118',
                'project' => 'CRM v1 Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'CRM v1 Prod RabbitMQ',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.221',
                'project' => 'CRM v1 Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'CRM v1 Prod MongoDB',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.119',
                'project' => 'CRM v1 Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'File Management Alfresco',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.65',
                'project' => 'File Management',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Ticketing OSTicket',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.66',
                'project' => 'Ticketing',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'CCTV Production',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.86',
                'project' => 'CCTV Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Puspeka Development',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.182',
                'project' => 'Puspeka Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Puspeka Production',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.185',
                'project' => 'Puspeka Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'KSBB Dinamis Development',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.236',
                'project' => 'KSBB Dinamis Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'KSBB Dinamis Production',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.235',
                'project' => 'KSBB Dinamis Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'KSBB Dinamis Production',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.243',
                'project' => 'KSBB Dinamis Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Rekrutmen Development',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.243',
                'project' => 'Rekrutmen Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Rekrutmen Production',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.244',
                'project' => 'Rekrutmen Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Kelas Warga Development',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.189',
                'project' => 'Kelas Warga Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Kelas Warga Production',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.190',
                'project' => 'Kelas Warga Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Minio TW Minio',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.174',
                'project' => 'Minio TW',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Karawangkab-dev Postgres',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.74',
                'project' => 'Karawangkab-dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Karawangkab-dev-Microk8s',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.75',
                'project' => 'Karawangkab-dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Karawangkab-dev Cache Server',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.78',
                'project' => 'Karawangkab-dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Karawangkab-dev- File Storage Server',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.79',
                'project' => 'Karawangkab-dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Karawangkab-prod Microk8s',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.236',
                'project' => 'Karawangkab-prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Karawangkab-prod Postgres',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.233',
                'project' => 'Karawangkab-prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Karawangkab-prod Cache Server',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.234',
                'project' => 'Karawangkab-prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Karawangkab-prod File Storage Server',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.235',
                'project' => 'Karawangkab-prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'PoC Dynatrace Managed Cluster',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.27',
                'project' => 'PoC Dynatrace',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'PoC Dynatrace ActiveGate',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.29',
                'project' => 'PoC Dynatrace',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'PoC Dynatrace Cluster Active Gate',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.17',
                'project' => 'PoC Dynatrace',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Docmost',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.87',
                'project' => 'Docmost',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'VM BLUD OSDM-Dev',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.163',
                'project' => 'VM BLUD OSDM-Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'OSDM Prod Front End',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.230',
                'project' => 'OSDM Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'OSDM Prod Back End',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.199',
                'project' => 'OSDM Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'web pusdatin dev',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.230',
                'project' => 'web pusdatin dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'BLUD_Aceh_DEV',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.167',
                'project' => 'BLUD_Aceh_DEV',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'lomba photo',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.194',
                'project' => 'lomba photo',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Jaki Staging On-Prem',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.70',
                'project' => 'Jaki Staging On-Prem',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Jaki Staging On-Prem',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.71',
                'project' => 'Jaki Staging On-Prem',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Jaki Staging On-Prem',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.72',
                'project' => 'Jaki Staging On-Prem',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Jaki Staging On-Prem',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.73',
                'project' => 'Jaki Staging On-Prem',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Jaki Staging On-Prem',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.74',
                'project' => 'Jaki Staging On-Prem',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'JakGo Prod',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.127',
                'project' => 'JakGo Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'JakGo DB',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.128',
                'project' => 'JakGo DB',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'AI Project gemilang.jsclab.id',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.198',
                'project' => 'AI Project',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];
        
        // Filter out duplicates and insert only new data
        $dataToInsert = collect($originalData)->filter(function ($item) use ($existingServers) {
            return !in_array($item['ip_address'], $existingServers);
        })->toArray();
        
        if (!empty($dataToInsert)) {
            echo "No new data to insert. All entries already exist.\n";
            return;
        }
        
        echo "Inserting " . count($dataToInsert) . " new VPN server entries...\n";
        DB::table('vpn_servers')->insert($dataToInsert);
        echo "Successfully inserted " . count($dataToInsert) . " VPN server entries.\n";
    }
}
