<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VpnServerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('vpn_servers')->insertOrIgnore([
            [
                'nama_sistem' => 'Jaki Dev Docker Swarm 1',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.130',
                'project' => 'Jaki Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Jaki Dev Docker Swarm 2',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.131',
                'project' => 'Jaki Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Jaki Dev Docker Swarm 3',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.132',
                'project' => 'Jaki Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Jaki Dev Database MySQL',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.138',
                'project' => 'Jaki Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Jaki Dev File Storage Minio',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.139',
                'project' => 'Jaki Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Jaki Dev Database PostgreSQL',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.203',
                'project' => 'Jaki Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Jaki Microservice Dev Kafka + Redis',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.184',
                'project' => 'Jaki Microservice Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Jaki Microservice Dev File Storage Minio',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.139',
                'project' => 'Jaki Microservice Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Jaki Microservice Dev Database PostgreSQL',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.203',
                'project' => 'Jaki Microservice Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Jaki Prod Docker Swarm 1',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.163',
                'project' => 'Jaki Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Jaki Prod Docker Swarm 2',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.164',
                'project' => 'Jaki Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Jaki Prod Docker Swarm 3',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.165',
                'project' => 'Jaki Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Jaki Prod Docker Swarm 4',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.166',
                'project' => 'Jaki Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Jaki Prod Docker Swarm 5',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.167',
                'project' => 'Jaki Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Jaki Prod Database MySQL',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.168',
                'project' => 'Jaki Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Jaki Prod File Storage Minio',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.169',
                'project' => 'Jaki Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Jaki Prod Database PostgreSQL 1',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.204',
                'project' => 'Jaki Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Jaki Prod Database PostgreSQL 2',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.43',
                'project' => 'Jaki Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Jaki Prod File Storage Minio',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.152',
                'project' => 'Jaki Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Jaki Prod Kafka + Redis',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.185',
                'project' => 'Jaki Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Jaki Staging Database 1',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.170',
                'project' => 'Jaki Staging',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Jaki Staging Database 2',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.171',
                'project' => 'Jaki Staging',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Jaki Staging Database 3',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.172',
                'project' => 'Jaki Staging',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Jaki Staging File Storage Minio 1',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.173',
                'project' => 'Jaki Staging',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Jaki Staging File Storage Minio 2',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.174',
                'project' => 'Jaki Staging',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Jaki Staging RabbitMQ + Redis',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.53',
                'project' => 'Jaki Staging',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'CRM Dev Docker Swarm',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.179',
                'project' => 'CRM Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'CRM Dev Database',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.184',
                'project' => 'CRM Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'CRM-Staging Docker Swarm',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.48',
                'project' => 'CRM-Staging',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'DB-CRM-Staging Database',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.49',
                'project' => 'DB-CRM-Staging',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'CRM Prod Docker Swarm',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.180',
                'project' => 'CRM Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'CRM Prod Database',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.181',
                'project' => 'CRM Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Website Corona Dev Docker Swarm + Database',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.87',
                'project' => 'Website Corona Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Website Corona Prod App + Database',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '10.15.39.58',
                'project' => 'Website Corona Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Website SIB Dev App + Database',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.60',
                'project' => 'Website SIB Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Website SIB Prod App',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.84',
                'project' => 'Website SIB Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Website SIB Prod Database MariaDB',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.205',
                'project' => 'Website SIB Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Web Corp Dev Docker Swarm + Database',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.60',
                'project' => 'Web Corp Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Web Corp Prod Docker Swarm',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.61',
                'project' => 'Web Corp Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Web Corp Prod Database MariaDB',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.62',
                'project' => 'Web Corp Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Web Corp Prod File Storage Minio',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.63',
                'project' => 'Web Corp Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Smart City Apps Dev Docker Swarm + Database',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.217',
                'project' => 'Smart City Apps Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Smart City Apps Prod Docker Swarm + Database 1',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.218',
                'project' => 'Smart City Apps Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Smart City Apps Prod Docker Swarm + Database 2',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.218',
                'project' => 'Smart City Apps Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'KSBB Dinamis Prod Docker Swarm + Database',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.235',
                'project' => 'KSBB Dinamis Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'KSBB Dinamis Dev Docker Swarm + Database',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.236',
                'project' => 'KSBB Dinamis Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Pantau Banjir Prod App + Database',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.85',
                'project' => 'Pantau Banjir Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'KSBB Dinamis Prod Docker Swarm + Database',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.235',
                'project' => 'KSBB Dinamis Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'LMS Study Jakarta Prod Docker Swarm',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.176',
                'project' => 'LMS Study Jakarta Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Pantau Banjir Dev App + Database',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.61',
                'project' => 'Pantau Banjir Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Smart Employee Dev Docker Swarm + Database',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.229',
                'project' => 'Smart Employee Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Pantau Banjir Prod App + Database',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.85',
                'project' => 'Pantau Banjir Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Buku Tamu Dev Docker Swarm + Database',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.241',
                'project' => 'Buku Tamu Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'LMS Study Jakarta Dev Docker Swarm + Database',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.175',
                'project' => 'LMS Study Jakarta Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Smart Change Prod API',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.112',
                'project' => 'Smart Change Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'LMS Study Jakarta Prod Docker Swarm',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.176',
                'project' => 'LMS Study Jakarta Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'LMS Study Jakarta Prod Database',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.177',
                'project' => 'LMS Study Jakarta Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Smart Change Prod Minio',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.115',
                'project' => 'Smart Change Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Smart Employee Dev Docker Swarm + Database',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.229',
                'project' => 'Smart Employee Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Portal Stunting Dev Docker Swarm + Database',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.186',
                'project' => 'Portal Stunting Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Smart Employee Prod Docker Swarm + Database',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.230',
                'project' => 'Smart Employee Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Plus Jakarta Dev ',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.190',
                'project' => 'Plus Jakarta Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Buku Tamu Dev Docker Swarm + Database',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.241',
                'project' => 'Buku Tamu Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Plus Jakarta On-Going ',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.189',
                'project' => 'Plus Jakarta On-Going',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Buku Tamu Prod Docker Swarm + Database',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.242',
                'project' => 'Buku Tamu Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Vaksinasi Corona Prod Docker Swarm',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '10.15.39.32',
                'project' => 'Vaksinasi Corona Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Smart Change Prod API',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.112',
                'project' => 'Smart Change Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Smart Change Prod FE',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.114',
                'project' => 'Smart Change Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Smart Change Prod Database',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.113',
                'project' => 'Smart Change Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Smart Change Prod Minio',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.115',
                'project' => 'Smart Change Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Smart Change Prod Nginx',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.116',
                'project' => 'Smart Change Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Sib-Worker1 K8S',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.207',
                'project' => 'Sib-Worker1',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Portal Stunting Dev Docker Swarm + Database',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.186',
                'project' => 'Portal Stunting Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'KSBB Corona Dev ',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.93',
                'project' => 'KSBB Corona Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Portal Stunting Prod Docker Swarm + Database',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.187',
                'project' => 'Portal Stunting Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'JakGo Dev App + Database',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.62',
                'project' => 'JakGo Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'City Data / Open Data Dev Database',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.225',
                'project' => 'City Data / Open Data Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'City Data / Open Data Prod Database',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.226',
                'project' => 'City Data / Open Data Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Plus Jakarta Dev ',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.190',
                'project' => 'Plus Jakarta Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'SIMPDP Dev Docker Swarm + Database',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.219',
                'project' => 'SIMPDP Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Plus Jakarta Prod ',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.50',
                'project' => 'Plus Jakarta Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Monitoring Apel Dev Docker Swarm (VM mati)',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.121',
                'project' => 'Monitoring Apel Dev',
                'is_active' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Plus Jakarta On-Going ',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.189',
                'project' => 'Plus Jakarta On-Going',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Monitoring Apel Dev Docker Swarm',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.125',
                'project' => 'Monitoring Apel Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Vaksinasi Corona Dev Docker Swarm',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.88',
                'project' => 'Vaksinasi Corona Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Monitoring Apel Dev Docker Swarm',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.144',
                'project' => 'Monitoring Apel Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Vaksinasi Corona Prod Docker Swarm 1',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '10.15.39.32',
                'project' => 'Vaksinasi Corona Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Vaksinasi Corona Prod Docker Swarm 2',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.188',
                'project' => 'Vaksinasi Corona Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Vaksinasi Corona Prod Docker Swarm 3',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.75',
                'project' => 'Vaksinasi Corona Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Vaksinasi Corona Prod Docker Swarm 4',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.76',
                'project' => 'Vaksinasi Corona Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Vaksinasi Corona Prod Database',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.129',
                'project' => 'Vaksinasi Corona Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Monitoring Apel Prod Docker Swarm (VM mati)',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.120',
                'project' => 'Monitoring Apel Prod',
                'is_active' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Sib-Master K8S',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.206',
                'project' => 'Sib-Master',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Sib-Worker1 K8S',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.207',
                'project' => 'Sib-Worker1',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Sib-Worker2 K8S',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.208',
                'project' => 'Sib-Worker2',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Monitoring Apel Prod Docker Swarm',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.126',
                'project' => 'Monitoring Apel Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'KSBB Corona Dev ',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.93',
                'project' => 'KSBB Corona Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Monitoring Apel Prod Docker Swarm',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.145',
                'project' => 'Monitoring Apel Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'KSBB Corona Prod ',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '10.15.39.63',
                'project' => 'KSBB Corona Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Monitoring Apel Prod Docker Swarm',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.147',
                'project' => 'Monitoring Apel Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'JakGo Dev App + Database',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.62',
                'project' => 'JakGo Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Monitoring Apel Prod Database MySQL',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.107',
                'project' => 'Monitoring Apel Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'GitLab ',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.103',
                'project' => 'GitLab',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'City Data / Open Data Dev Database',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.225',
                'project' => 'City Data / Open Data Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'City Data / Open Data Prod Database',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.226',
                'project' => 'City Data / Open Data Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Backup Backup B',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.210',
                'project' => 'Backup',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'JAKI Staging Database',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.227',
                'project' => 'JAKI Staging',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Docker Registry Untuk project lama',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.102',
                'project' => 'Docker Registry',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Log Management Grafana',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.228',
                'project' => 'Log Management',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'SIMPDP Dev Docker Swarm + Database',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.219',
                'project' => 'SIMPDP Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Rancher Old Rancher Cluster project2 lama versi dev',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.102',
                'project' => 'Rancher Old',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Monitoring Apel Dev Docker Swarm (VM mati) 1',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.120',
                'project' => 'Monitoring Apel Dev',
                'is_active' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Monitoring Apel Dev Docker Swarm (VM mati) 2',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.121',
                'project' => 'Monitoring Apel Dev',
                'is_active' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Monitoring Apel Dev Docker Swarm (VM mati) 3',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.122',
                'project' => 'Monitoring Apel Dev',
                'is_active' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Monitoring Apel Dev Docker Swarm 1',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.125',
                'project' => 'Monitoring Apel Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Monitoring Apel Dev Docker Swarm 2',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.126',
                'project' => 'Monitoring Apel Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Monitoring Apel Dev Docker Swarm 3',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.144',
                'project' => 'Monitoring Apel Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Monitoring Apel Dev Docker Swarm 4',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.145',
                'project' => 'Monitoring Apel Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Monitoring Apel Dev Docker Swarm 5',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.146',
                'project' => 'Monitoring Apel Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Monitoring Apel Dev Docker Swarm 6',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.147',
                'project' => 'Monitoring Apel Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Monitoring Apel Dev Docker Swarm 7',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.148',
                'project' => 'Monitoring Apel Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Monitoring Apel Dev Database MySQL',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.106',
                'project' => 'Monitoring Apel Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'CRM v1 Staging Rancher Cluster',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.141',
                'project' => 'CRM v1 Staging',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Monitoring Apel Prod Docker Swarm (VM mati) 1',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.120',
                'project' => 'Monitoring Apel Prod',
                'is_active' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Monitoring Apel Prod Docker Swarm (VM mati) 2',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.121',
                'project' => 'Monitoring Apel Prod',
                'is_active' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Monitoring Apel Prod Docker Swarm (VM mati) 3',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.122',
                'project' => 'Monitoring Apel Prod',
                'is_active' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Monitoring Apel Prod Docker Swarm 1',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.125',
                'project' => 'Monitoring Apel Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Monitoring Apel Prod Docker Swarm 2',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.126',
                'project' => 'Monitoring Apel Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Monitoring Apel Prod Docker Swarm 3',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.144',
                'project' => 'Monitoring Apel Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Monitoring Apel Prod Docker Swarm 4',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.145',
                'project' => 'Monitoring Apel Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Monitoring Apel Prod Docker Swarm 5',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.146',
                'project' => 'Monitoring Apel Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Monitoring Apel Prod Docker Swarm 6',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.147',
                'project' => 'Monitoring Apel Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Monitoring Apel Prod Docker Swarm 7',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.148',
                'project' => 'Monitoring Apel Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Monitoring Apel Prod Database MySQL',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.107',
                'project' => 'Monitoring Apel Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'CRM v1 Prod MongoDB',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.119',
                'project' => 'CRM v1 Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'GitLab ',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.103',
                'project' => 'GitLab',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Ticketing OSTicket App + Database',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.66',
                'project' => 'Ticketing',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Backup Backup Old
Storage-nya penuh',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.137',
                'project' => 'Backup',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Backup Backup A (DB)',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.209',
                'project' => 'Backup',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Backup Backup B (Gitlab)',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.210',
                'project' => 'Backup',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Pantau Isoman Dev Docker Swarm + Database',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.53',
                'project' => 'Pantau Isoman Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Portainer ',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.134',
                'project' => 'Portainer',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Pusbin Dev Docker Swarm + Database',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.94',
                'project' => 'Pusbin Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Docker Registry Untuk project lama',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.102',
                'project' => 'Docker Registry',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'KSBB Dinamis Dev Docker Swarm + Database',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.236',
                'project' => 'KSBB Dinamis Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Log Management Grafana',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.228',
                'project' => 'Log Management',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Rancher Old Rancher Management untuk project2 lama
Ga bisa diakses',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.110',
                'project' => 'Rancher Old',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Rancher Old Rancher Cluster project2 lama versi dev 1',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.102',
                'project' => 'Rancher Old',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Rancher Old Rancher Cluster project2 lama versi dev 2',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.116',
                'project' => 'Rancher Old',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Rancher Old Rancher Cluster project2 lama versi prod 1',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.104',
                'project' => 'Rancher Old',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Rancher Old Rancher Cluster project2 lama versi prod 2',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.115',
                'project' => 'Rancher Old',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Jaki Staging On-Prem ',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.71',
                'project' => 'Jaki Staging On-Prem',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'CRM v1 Rancher Rancher Management CRM v1 Staging n Prod
Ga bisa diakses',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.223',
                'project' => 'CRM v1 Rancher',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Jaki Staging On-Prem ',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.73',
                'project' => 'Jaki Staging On-Prem',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'CRM v1 Dev Rancher Cluster 1',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.102',
                'project' => 'CRM v1 Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'CRM v1 Dev Rancher Cluster 2',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.116',
                'project' => 'CRM v1 Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'CRM v1 Dev Database',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.106',
                'project' => 'CRM v1 Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'CRM v1 Dev Minio',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.105',
                'project' => 'CRM v1 Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'CRM v1 Dev Redis',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.118',
                'project' => 'CRM v1 Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'CRM v1 Dev RabbitMQ',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.221',
                'project' => 'CRM v1 Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'CRM v1 Staging Rancher Cluster 1',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.127',
                'project' => 'CRM v1 Staging',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'CRM v1 Staging Rancher Cluster 2',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.141',
                'project' => 'CRM v1 Staging',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'CRM v1 Staging Database',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.106',
                'project' => 'CRM v1 Staging',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'CRM v1 Staging Minio',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.105',
                'project' => 'CRM v1 Staging',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'CRM v1 Staging Redis',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.118',
                'project' => 'CRM v1 Staging',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'CRM v1 Staging RabbitMQ',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.221',
                'project' => 'CRM v1 Staging',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'CRM v1 Prod Rancher Cluster 1',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.224',
                'project' => 'CRM v1 Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'CRM v1 Prod Rancher Cluster 2',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.142',
                'project' => 'CRM v1 Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'CRM v1 Prod Rancher Cluster 3',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.143',
                'project' => 'CRM v1 Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'CRM v1 Prod Database',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.107',
                'project' => 'CRM v1 Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'CRM v1 Prod Minio',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.105',
                'project' => 'CRM v1 Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'CRM v1 Prod Redis',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.118',
                'project' => 'CRM v1 Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'CRM v1 Prod RabbitMQ',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.221',
                'project' => 'CRM v1 Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'CRM v1 Prod MongoDB',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.119',
                'project' => 'CRM v1 Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'File Management Alfresco App + Database + Minio',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.65',
                'project' => 'File Management',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Ticketing OSTicket App + Database',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.66',
                'project' => 'Ticketing',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'CCTV Prod App + Database',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.86',
                'project' => 'CCTV Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Puspeka Dev Docker Swarm + Database',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.182',
                'project' => 'Puspeka Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Puspeka Prod Docker Swarm + Database',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.185',
                'project' => 'Puspeka Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Pantau Isoman Dev Docker Swarm + Database',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.53',
                'project' => 'Pantau Isoman Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Pantau Isoman Prod Docker Swarm + Database',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.54',
                'project' => 'Pantau Isoman Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Pusbin Dev Docker Swarm + Database',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.94',
                'project' => 'Pusbin Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Pusbin Demo Docker Swarm + Database',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.91',
                'project' => 'Pusbin Demo',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'KSBB Dinamis Dev Docker Swarm + Database',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.236',
                'project' => 'KSBB Dinamis Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'KSBB DInamis Prod Docker Swarm + Database',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.235',
                'project' => 'KSBB DInamis Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Rekrutmen Dev Docker Swarm + Database',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.243',
                'project' => 'Rekrutmen Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Rekrutmen Prod Docker Swarm + Database',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.244',
                'project' => 'Rekrutmen Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Kelas Warga Dev K8S + Database',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.189',
                'project' => 'Kelas Warga Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Kelas Warga Prod K8S + Database',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.190',
                'project' => 'Kelas Warga Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Minio TW Minio',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.3.174',
                'project' => 'Minio TW',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Karawangkab-dev Postgres',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.74',
                'project' => 'Karawangkab-dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Karawangkab-dev-Microk8s',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.75',
                'project' => 'Karawangkab-dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Karawangkab-dev Cache Server, Redis',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.78',
                'project' => 'Karawangkab-dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Karawangkab-dev- File Storage Server, Minio',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.79',
                'project' => 'Karawangkab-dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Karawangkab-prod Microk8s',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.236',
                'project' => 'Karawangkab-prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Karawangkab-prod Postgres',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.233',
                'project' => 'Karawangkab-prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Karawangkab-prod Cache Server, Redis',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.234',
                'project' => 'Karawangkab-prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Karawangkab-prod File Storage Server, Minio',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.235',
                'project' => 'Karawangkab-prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'PoC Dynatrace Dynatrace Managed Cluster',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.27',
                'project' => 'PoC Dynatrace',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'PoC Dynatrace ActiveGate',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.29',
                'project' => 'PoC Dynatrace',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'PoC Dynatrace Cluster Active Gate',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.17',
                'project' => 'PoC Dynatrace',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Docmost ',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.87',
                'project' => 'Docmost',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'VM BLUD OSDM-Dev ',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.163',
                'project' => 'VM BLUD OSDM-Dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'OSDM Prod Front End',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '118.98.230.27',
                'project' => 'OSDM Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'OSDM Prod  Back End',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.5.199',
                'project' => 'OSDM Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'web pusdatin dev ',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.230',
                'project' => 'web pusdatin dev',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'BLUD_Aceh_DEV ',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.167',
                'project' => 'BLUD_Aceh_DEV',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'lomba photo ',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.194',
                'project' => 'lomba photo',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Jaki Staging On-Prem ',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.70',
                'project' => 'Jaki Staging On-Prem',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Jaki Staging On-Prem ',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.71',
                'project' => 'Jaki Staging On-Prem',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Jaki Staging On-Prem ',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.72',
                'project' => 'Jaki Staging On-Prem',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Jaki Staging On-Prem ',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.73',
                'project' => 'Jaki Staging On-Prem',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'Jaki Staging On-Prem ',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.74',
                'project' => 'Jaki Staging On-Prem',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'JakGo Prod ',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '10.15.39.127',
                'project' => 'JakGo Prod',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'JakGo DB ',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '10.15.39.128',
                'project' => 'JakGo DB',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama_sistem' => 'AI Project gemilang.jsclab.id',
                'server_location' => 'Jakarta, Indonesia',
                'ip_address' => '192.168.11.198',
                'project' => 'AI Project',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
